### ISSUE TITLE
Not Compatible with SotS Update

### ISSUE THREAD

**Issue by n64kev** [KaanGaming/EngineerTurretTaunt#4]

**Comment by KaanGaming** [comment]
I know the new DLC breaks a lot of mods, so inevitably the DLC would break this mod as well, though I'll just most likely have to update the R2API dependencies. I'll add the correct dependencies for the SotS update and the mod update will be out either today or tomorrow if nothing goes wrong, and I'll **close this issue** when the fix is pushed to thunderstore.io, sorry for the delay.

**Comment by KaanGaming** [comment]
OK, the mod seems to work fine on the new SotS update. The mod update will be out tomorrow alongside the UltrakillTimer mod's update

**Comment by kaangamgimginnka** [comment]
Should be fixed now, if the issue still persists please reopen the issue
